language: node_js

node_js:
  - "8"

branches:
  only:
    - master

services: 
  - postgresql

env:
  - TEST_DB_NAME=cashcow_test DB_PORT=5432 DB_NAME=cashcow

before_script:
  - psql -c 'create database cashcow_test;' -U postgres

# script: npm install && npm test

