language: node_js

node_js:
  - "8"

branches:
  only:
    - master

services: 
  - postgresql

before_script:
  - psql -c 'create database cashcow_tes;' -U postgres

after_script:
  - psql -c 'drop database cashcow_test;' -U postgres

script: npm install && npm test